### ISSUE TITLE
Texify doesn't work in Mac

### ISSUE THREAD

**Issue by luizaandrade** [luizaandrade/stata-dynamic-docs#1]

**Comment by bbdaniels** [comment]
two different problems:

1) Should not use `" "` around filename; `texify` does not handle that correctly
2) bash (`!`) can't find `pdflatex`

resolution: don't use `texify`.

Instead, just call the LaTeX compiler directly.
Open `terminal`, type `which pdflatex`
Terminal will return the path to the binary file, such as:
```
Benjamins-iMac:~ bbdaniels$ which pdflatex
/Users/bbdaniels/bin/pdflatex
```

This path can be used directly from Stata as follows:
`! /Users/bbdaniels/bin/pdflatex "${output}/main_doc.tex/"`

**Comment by luizaandrade** [comment]
Thanks, @bbdaniels !
